# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c9ab722777323c167eb9d419f5c9c69ead6a9e039317035650ec0c4cb96a625f4f09986a682dca48beda506c692bdefec168503a1bea0b10f9fd22ab2df0caa

test:
  secret_key_base: 7b8267b6062f2dfe077baa3cbc09de8f114cb0951e16ee5e198a257bd1beb7583f23eb9012c2d6faf5b29f5a3aba253b660d155ac078da336eb8650e4bc86cf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
